version: '3'

services:
  env:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
        - ..:/workspace:cached
        - $SSH_AUTH_SOCK:/ssh-agent
    environment:
      - SSH_AUTH_SOCK=/ssh-agent

